services:
  stellar:
    image: stellar/quickstart
    container_name: stellar
    ports:
      - "8000:8000"
    command: ["--local"]
  
  app:
    image: dalloglio/rust-with-stellar-cli:local
    container_name: app
